/** Agent definitions (§12). Each agent is bounded; the orchestrator runs them in order. */
export interface AgentDefinition {
  id: string;
  name: string;
  purpose: string;
  inputs: string[];
  outputs: string[];
  allowedTools: string[];
  prohibitedActions: string[];
  state: "stateless" | "assessment-scoped";
  handoffCondition: string;
  retryPolicy: string;
  failureBehavior: string;
  humanApprovalBoundary: string;
  auditEvents: string[];
  deterministicFallback: string;
  /** Does the demo edition run this agent? */
  demo: boolean;
}

const NO_SECRETS = "Never request, store or emit credentials, tokens, keys or connection strings.";
const base = { state: "assessment-scoped" as const, retryPolicy: "none: deterministic; rerun the assessment", failureBehavior: "fail the stage, record the error in progress, keep earlier outputs" };

export const AGENTS: AgentDefinition[] = [
  { id: "intake", name: "Intake and Scope Agent", purpose: "Collect source/destination, tenant & subscription relationship, region, landing-zone status, downtime/RTO/RPO, intent.", inputs: ["questionnaire answers"], outputs: ["MigrationIntent with assumedFields"], allowedTools: ["defaultIntent"], prohibitedActions: [NO_SECRETS], ...base, handoffCondition: "intent built", humanApprovalBoundary: "none", auditEvents: ["intent.created"], deterministicFallback: "defaults labelled as assumptions", demo: true },
  { id: "authn", name: "Authentication and Authorization Agent", purpose: "Establish read-only discovery context; report permission gaps.", inputs: ["session", "credential kind"], outputs: ["Principal", "permission gaps"], allowedTools: ["Entra OIDC (enterprise)", "managed identity", "workload identity federation"], prohibitedActions: ["service principal secrets in code", "elevating beyond requested level", NO_SECRETS], ...base, handoffCondition: "principal established", humanApprovalBoundary: "any level above planning", auditEvents: ["auth.level.granted"], deterministicFallback: "demo principal at planning level", demo: true },
  { id: "discovery", name: "Discovery Agent", purpose: "Azure Resource Graph discovery and service-API enrichment; detect partial visibility; redact secrets.", inputs: ["scope"], outputs: ["NormalizedResource[] with observed-from-azure-api evidence"], allowedTools: ["DiscoveryProvider.discover (read-only)"], prohibitedActions: ["any write", NO_SECRETS], ...base, handoffCondition: "resources normalized", humanApprovalBoundary: "none (read-only)", auditEvents: ["discovery.completed", "discovery.partial"], deterministicFallback: "fixture provider", demo: false },
  { id: "csv-discovery", name: "CSV Discovery Agent", purpose: "Parse resources.csv, normalize headers/values, track provenance, reject unsafe input, report missing fields.", inputs: ["csv text"], outputs: ["IngestionResult"], allowedTools: ["ingestResourcesCsv"], prohibitedActions: ["executing uploaded content", "logging raw rows", NO_SECRETS], ...base, handoffCondition: "≥1 resource or explicit error", humanApprovalBoundary: "none", auditEvents: ["ingest.completed"], deterministicFallback: "n/a (deterministic)", demo: true },
  { id: "dependencies", name: "Dependency Mapping Agent", purpose: "Parent/child (discovered) and type/co-location edges (inferred); sequence resources.", inputs: ["resources"], outputs: ["dependency map", "sequence"], allowedTools: ["mapDependencies", "sequence"], prohibitedActions: ["labelling inferred edges as discovered"], ...base, handoffCondition: "map built", humanApprovalBoundary: "none", auditEvents: ["dependencies.mapped"], deterministicFallback: "n/a", demo: true },
  { id: "evidence", name: "Support Matrix and Evidence Agent", purpose: "Load versioned rules; detect stale, duplicate and conflicting rules; cite sources.", inputs: ["rules directory"], outputs: ["LoadedRules", "snapshot"], allowedTools: ["loadRules"], prohibitedActions: ["inventing support states", "editing rules at runtime"], ...base, handoffCondition: "rules valid", failureBehavior: "abort: an invalid rule corpus must not produce decisions", humanApprovalBoundary: "none", auditEvents: ["rules.loaded", "rules.stale"], deterministicFallback: "n/a", demo: true },
  { id: "classification", name: "Classification and Decision Agent", purpose: "Assign disposition per dimension, reason codes, alternatives, confidence; flag human review.", inputs: ["resources", "rules", "dependencies", "intent", "landing-zone profile"], outputs: ["ResourceDecisionRecord[]"], allowedTools: ["classifyResource"], prohibitedActions: ["high confidence from low evidence", "ASR as default migration tool", "unsupported without alternative"], ...base, handoffCondition: "every resource has a record", humanApprovalBoundary: "none (recommendation only)", auditEvents: ["decision.created"], deterministicFallback: "unknown-requires-validation", demo: true },
  { id: "landing-zone", name: "Landing Zone Agent", purpose: "Determine destination MG/subscription/RG/network/DNS/identity/logging/naming/tags/budget/regional constraints.", inputs: ["intent", "authenticated inspection (enterprise)"], outputs: ["LandingZoneProfile", "prerequisites"], allowedTools: ["profileFromIntent", "landingZonePrerequisites"], prohibitedActions: ["claiming validation of a real landing zone in demo"], ...base, handoffCondition: "profile built", humanApprovalBoundary: "none", auditEvents: ["landingzone.profiled"], deterministicFallback: "sample profile", demo: true },
  { id: "iac", name: "Infrastructure as Code Agent", purpose: "Generate modular Terraform for recreate dispositions.", inputs: ["Assessment"], outputs: ["terraform/**"], allowedTools: ["generateTerraform"], prohibitedActions: ["plaintext secrets", "import blocks without inspection", "claiming production readiness"], ...base, handoffCondition: "files generated", humanApprovalBoundary: "apply", auditEvents: ["artifact.terraform"], deterministicFallback: "skip unsupported types with reason", demo: true },
  { id: "tooling", name: "Migration Tooling Agent", purpose: "Generate PowerShell/Azure CLI scaffolding: dry-run, preconditions, structured logs, exit codes.", inputs: ["Assessment"], outputs: ["scripts/**"], allowedTools: ["generateScripts"], prohibitedActions: ["embedding credentials", "blind retries", "executing"], ...base, handoffCondition: "files generated", humanApprovalBoundary: "execution", auditEvents: ["artifact.scripts"], deterministicFallback: "n/a", demo: true },
  { id: "data", name: "Data Migration Agent", purpose: "Define online/offline method, sync passes, freeze, final sync, cutover, validation, rollback per data-bearing resource.", inputs: ["decisions"], outputs: ["reconciliation plan"], allowedTools: ["buildValidationPlan"], prohibitedActions: ["conflating data path with infrastructure move"], ...base, handoffCondition: "plan built", humanApprovalBoundary: "data cutover", auditEvents: ["artifact.reconciliation"], deterministicFallback: "n/a", demo: true },
  { id: "dr", name: "Backup and Disaster Recovery Agent", purpose: "Identify vault/backup/ASR/failover re-protection needs after migration; keep DR distinct from migration.", inputs: ["decisions"], outputs: ["secondary actions"], allowedTools: ["classification secondary actions"], prohibitedActions: ["selecting ASR as migration path"], ...base, handoffCondition: "actions attached", humanApprovalBoundary: "replication enablement", auditEvents: ["dr.evaluated"], deterministicFallback: "n/a", demo: true },
  { id: "cost", name: "Cost and Capacity Agent", purpose: "Regional availability, quota, SKU, licensing, coexistence/transfer cost.", inputs: ["decisions", "authenticated SKU/quota APIs (enterprise)"], outputs: ["availability states"], allowedTools: ["Azure quota/SKU APIs (enterprise, read-only)"], prohibitedActions: ["asserting availability without evidence"], ...base, handoffCondition: "states recorded", humanApprovalBoundary: "none", auditEvents: ["capacity.evaluated"], deterministicFallback: "unknown + requires-authenticated-validation", demo: false },
  { id: "waves", name: "Wave Planning and Cutover Agent", purpose: "Application groups, waves, sequencing, entry/exit criteria, cutover, rollback, hypercare.", inputs: ["decisions"], outputs: ["WavePlan", "runbooks"], allowedTools: ["planWaves", "generateRunbooks"], prohibitedActions: ["scheduling unknowns"], ...base, handoffCondition: "plan built", humanApprovalBoundary: "cutover", auditEvents: ["waves.planned"], deterministicFallback: "type-based waves", demo: true },
  { id: "validation", name: "Validation Agent", purpose: "Checklist and test plan across infra/config/identity/network/security/data/perf/monitoring/backup/DR/app.", inputs: ["decisions"], outputs: ["validation/**"], allowedTools: ["buildValidationPlan"], prohibitedActions: ["marking items validated"], ...base, handoffCondition: "plan built", humanApprovalBoundary: "none", auditEvents: ["artifact.validation"], deterministicFallback: "n/a", demo: true },
  { id: "security", name: "Security and Compliance Agent", purpose: "Excess privilege, residency, encryption/CMK, secret transfer, private connectivity, Defender, policy.", inputs: ["decisions", "intent"], outputs: ["risk/prerequisite entries"], allowedTools: ["rule risks", "landing-zone prerequisites"], prohibitedActions: ["downgrading a security finding"], ...base, handoffCondition: "entries attached", humanApprovalBoundary: "none", auditEvents: ["security.evaluated"], deterministicFallback: "n/a", demo: true },
  { id: "report", name: "Report and Evidence Agent", purpose: "Executive, engineering, security, data reports; audit records; artifact manifest.", inputs: ["Assessment"], outputs: ["reports/**", "evidence/**", "manifest.json"], allowedTools: ["buildBundle"], prohibitedActions: ["omitting disclaimers"], ...base, handoffCondition: "bundle built", humanApprovalBoundary: "none", auditEvents: ["artifact.bundle"], deterministicFallback: "n/a", demo: true },
  { id: "safety", name: "Safety Agent", purpose: "Verify facts/assumptions separated, confidence ≤ evidence, demo labelled, no credentials, no approval bypass, no output misrepresented as validated.", inputs: ["Assessment", "bundle"], outputs: ["safety findings"], allowedTools: ["runSafetyChecks"], prohibitedActions: ["suppressing findings"], ...base, handoffCondition: "always runs last", failureBehavior: "findings attached; a critical finding fails the assessment", humanApprovalBoundary: "none", auditEvents: ["safety.checked"], deterministicFallback: "n/a", demo: true },
  { id: "approval-gate", name: "Human Approval Gate", purpose: "Require explicit approval before role assignments, replication, production deploy, failover, DNS, data cutover, source deletion, destructive or irreversible operations.", inputs: ["Principal", "operation", "target"], outputs: ["gate decision"], allowedTools: ["gate"], prohibitedActions: ["auto-approval", "demo execution"], state: "stateless", retryPolicy: "n/a", failureBehavior: "deny", handoffCondition: "n/a", humanApprovalBoundary: "this agent is the boundary", auditEvents: ["approval.requested", "approval.granted", "approval.denied"], deterministicFallback: "deny", demo: true },
];
